language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

sudo: false
dist: xenial

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: ruby-head
