language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head

sudo: false

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: ruby-head
