language: ruby

rvm:
  - 2.2.2
  - 2.3.3
  - 2.4.0
  - ruby-head

sudo: false

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: ruby-head
